<?xml version="1.0" encoding="utf-8"?><Database Name="Demo" Class="DemoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-P9B24QG\QUYET_TRAN;Initial Catalog=Demo;Integrated Security=True" SettingsObjectName="WindowsFormsApp2.Properties.Settings" SettingsPropertyName="DemoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PhongBan" Member="PhongBans">
    <Type Name="PhongBan">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PhongBan_SinhVien" Member="SinhViens" ThisKey="ID" OtherKey="ID" Type="SinhVien" />
    </Type>
  </Table>
  <Table Name="dbo.SinhVien" Member="SinhViens">
    <Type Name="SinhVien">
      <Column Name="IDStudent" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="homeTown" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PhongBan_SinhVien" Member="PhongBan" ThisKey="ID" OtherKey="ID" Type="PhongBan" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Function Name="dbo.NhanVien_Update" Method="NhanVien_Update">
    <Parameter Name="fullName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="homeTown" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="IDStudent" Parameter="iDStudent" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.NhanVien_Delete" Method="NhanVien_Delete">
    <Parameter Name="IDStudent" Parameter="iDStudent" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.NhanVien_Insert" Method="NhanVien_Insert">
    <Parameter Name="fullName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="homeTown" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.NhanVien_SelectID" Method="NhanVien_SelectID">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="NhanVien_SelectIDResult">
      <Column Name="IDStudent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="homeTown" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PhongBan_Delete" Method="PhongBan_Delete">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PhongBan_Insert" Method="PhongBan_Insert">
    <Parameter Name="Department" Parameter="department" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PhongBan_SelectAll" Method="PhongBan_SelectAll">
    <ElementType Name="PhongBan_SelectAllResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PhongBan_Update" Method="PhongBan_Update">
    <Parameter Name="Department" Parameter="department" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>