//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public int IDStudent { get; set; }
        public string fullName { get; set; }
        public string homeTown { get; set; }
        public Nullable<int> ID { get; set; }
    
        public virtual PhongBan PhongBan { get; set; }
    }
}
